version: 2

defaults:
  # name of a file in the config/live directory
  # or an absolute path to a config file
  config: "latest.json"

  # uncomment settings to enable them

  # absolute path to a keys file
  # api_keys: /home/ubuntu/passivbot/api-keys.json

  # assigned_balance: 0
  # market_type: "futures"
  # leverage: 7

  # long_mode: "n"
  # long_exposure: 0
  # long_min_markup: 0
  # long_markup_range: 0

  # short_mode: "m"
  # short_exposure: 0
  # short_min_markup: 0
  # short_markup_range: 0

# it is highly recommended to read the docs/manager.md
# for the advanced instances configuration
instances:
  - user: "binance_0x"
    symbols:
      - "BTCUSDT"
      - "ETHUSDT"
